### ISSUE TITLE
Registar should be published

### ISSUE THREAD

**Issue by guusdk** [xsf/registrar#28]
The registar used to be accessible at https://xmpp.org/registrar/ but no longer is (likely caused by the server loss we suffered earlier this year).

**Comment by guusdk** [comment]
The original URL now lists directory content, which is an improvement. I'm leaving this open as a reminder to add a nicer index page (and possibly link to it from the XSF website).

**Comment by SamWhited** [comment]
There is now an index page. It could still be nicer as it doesn't match the rest of the website, but I think this is an issue for the web repo now.

**Comment by guusdk** [comment]
Things can always be nicer. The original issue is resolved though, so I'll close this.
