### ISSUE TITLE
Registrar section is not updated

### ISSUE THREAD

**Issue by Neustradamus** [xsf/registrar#31]
There are missing files:
- https://xmpp.org/registrar/

Linked to:
- https://github.com/xsf/xmpp.org/issues/422

**Comment by Neustradamus** [comment]
Dear @SamWhited: Can you reopen this ticket?

It is not up-to-date, you can see here: https://xmpp.org/registrar/
- Last Updated: 2011-02-22

**Comment by SamWhited** [comment]
This has nothing to do with the registrar, I'll talk to the iteam about it.
