### ISSUE TITLE
Incorrect listing for  `urn:ietf:params:xml:ns:xmpp-session` 

### ISSUE THREAD

**Issue by guusdk** [xsf/registrar#34]
The stream feature `urn:ietf:params:xml:ns:xmpp-session` was defined in section 3 of RFC 3921, but has been dropped in 6120/21 
 
The feature is incorrectly listed in https://xmpp.org/registrar/namespaces.html with a reference to 6121. That should probably point to 3921 instead.

**Comment by guusdk** [comment]
Possibly introduced by using an XML entity to refer to the RFCs, that got updated from 3921 to 6121.

Possibly relevant: https://tools.ietf.org/html/draft-cridland-xmpp-session-01

**Comment by Neustradamus** [comment]
@guusdk: Thanks for your issue, it is linked to:
- https://github.com/xsf/xmpp.org/issues/422 (29 Mar 2018)
- https://github.com/xsf/registrar/issues/31 (21 Aug 2019)
